python gerar_informe_rendimentos.py  `
--input-file data\Extrato-01-01-2025-a-31-12-2026-OFX.ofx  `
--output-pdf data\informe.pdf `
--exercicio 2026 `
--ano-calendario 2025 `
--fonte-cnpj "33.352.491/0001-99" `
--fonte-nome "GUMERCINDO BALAS LTDA" `
--beneficiario-cpf "971.453.760-67" `
--beneficiario-nome "GUMERCINDO  DA SILVA SAURO" `
--responsavel-nome "MICHAEL JACKSON SCHWARZENEGGER DA SILVA" `
--data "28/02/2026" `
--natureza "RENDIMENTO DO TRABALHO ASSALARIADO NO PAIS" `
--rendimentos-keyword "PRO-LABORE" `
--rendimentos-positivos `
--previdencia-keyword "RETENCAO INSS" `
--irrf-keyword "IRRF A RECOLHER" `
--exceto-prolabore-keyword "ANTECIPACAO DE DIVIDENDOS" `
--audit-excel data\auditoria.xlsx
